### ISSUE TITLE
core dump

### ISSUE THREAD

**Issue by saeid93** [sigdata/im_benchmarking#1]
Hi
every time I try to run the code:

`saeid@saied-pc:~/R projects/IEEEconf/IM  mehtods/1 Seminal/2 Imrank + Irie + static_greedy (not OK)/im_benchmarking-master/imrank$ ./mymain input.csv 50 1 10 Degree
`

I got the following error can you please tell me what I'm doing wrong?

`network info:2  0
Segmentation fault (core dumped)
`
I think it is some problem with my input file. Here is my input file:

[input.txt](https://github.com/sigdata/im_benchmarking/files/2592602/input.txt)

it is an adjacency list with the third column as diffusion probabilities.

**Comment by akhilarora** [comment]
Hi Saeid,

We need more details from your end, such as:
1. Where was the code downloaded from?
2. Did you recompile the source to generate fresh binaries or are you using the one that was present in the code repo that you downloaded?
3. What is your OS distribution and the version?
4. Which version of g++/gcc are you using to compile the source?

The above details would help us in trying to help you out in pinpointing to the exact issue.

Thanks.

**Comment by saeid93** [comment]
Hi thank you for your response
I am really sorry. I mistakenly wrote my problem about another source code not related to this repository here.
I have updated my issue.
I have downloaded this source code from this repo and compiled and run it.
I use Ubuntu 16.04 and my g++ 5.4.0

**Comment by akhilarora** [comment]
I am closing this issue then. I hope you are able to run your code then!

**Comment by saeid93** [comment]
Dear Akhil I think I wasn't able to express what I meant. I still have the problem and if you see I have updated the issue. What I said is that I asked the wrong question but I still have one :)
could you please take a look at the updated issue?

**Comment by sainyam** [comment]
Hi Saeid,

With the attached input it will work. Changes you need to do: 
1) First line should have n and m
2) Instead of ',' use space 
Please let us know if you still face any issue.

[input.txt](https://github.com/sigdata/im_benchmarking/files/2593127/input.txt)

**Comment by saeid93** [comment]
Thank u for your response
That's solved the problem!
